# Generated by Django 5.2.7 on 2025-10-17 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_report_options_remove_report_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='report_image',
            field=models.ImageField(blank=True, null=True, upload_to='reports/'),
        ),
    ]
