# Generated by Django 5.2.7 on 2025-10-17 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_report_report_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='patient_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
